---
title: Data Recoding
author: R package build
date: '2022-02-23'
slug: data-recoding
categories: []
tags: []
---
```{r}
library(tidyverse)
```

```{r}
rel_inc <- read_csv('https://raw.githubusercontent.com/ellaprotz/tidyverse/main/relig-income.csv')
rel_inc
```

#Rename Column
```{r}
rel_inc %>%
  rename( 
    religion = `Religious tradition`, 
    n = `Sample Size` 
  )
```

#Pivot Longer
```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer( 
    cols = -c(religion, n),   # all but religion and n 
    names_to = "income",  
    values_to = "proportion" 
  )
```

#Calculate Frequencies

```{r}
rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion"
  ) %>%
  mutate(frequency = round('proportion' * '))
```

```{r}
rel_inc_long <- rel_inc %>% 
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer(
    cols = -c(religion, n), 
    names_to = "income", 
    values_to = "proportion"
  ) %>%
  mutate(frequency = round(proportion * n))
```

# Bar Plot
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency)) +
  geom_col()
```

