---
title: Data types
author: R package build
date: '2022-02-21'
slug: data-types
categories: []
tags: []
---
```{r}
library(tidyverse)
```

```{r}
cat_lovers<- read.csv('https://raw.githubusercontent.com/ellaprotz/tidyverse/main/cat-lovers.csv')
names(cat_lovers)
```

## Bad data
```{r}
glimpse(cat_lovers)
cat_lovers %>%
  summarise(mean_cats = mean(number_of_cats))
```

```{r}
cat_lovers %>%
  summarise(mean_cats = mean(number_of_cats, na.rm = TRUE))
```

```{r}
cat_lovers %>%
  mutate(number_of_cats = case_when(
    name == "Ginger Clark" ~ 2,
    name == "Doug Bass"    ~ 3,
    TRUE                   ~ as.numeric(number_of_cats)
    )) %>%
  summarise(mean_cats = mean(number_of_cats))
```

## Mean of Cats
```{r}
cat_lovers %>%
  mutate(
    number_of_cats = case_when(
      name == "Ginger Clark" ~ "2",
      name == "Doug Bass"    ~ "3",
      TRUE                   ~ number_of_cats
      ),
    number_of_cats = as.numeric(number_of_cats)
    ) %>%
  summarise(mean_cats = mean(number_of_cats))
```

## Data Types - Coercion
## Logical and Character
```{r}
#logical - boolean values TRUE and FALSE
typeof(TRUE)
#character - character strings
typeof("hello")
```

## Double and Integer
```{r}
#double - floating point numerical values (default numerical type)
typeof(1.335)
typeof(7)
#integer - integer numerical values (indicated with an L)
typeof(7L)
typeof(1:3)
```

##Concatenation
```{r}
#Vectors can be constructed using the c() function.
c(1, 2, 3)
c("Hello", "World!")
c(c("hi", "hello"), c("bye", "jello"))
```

## Converting between types
```{r}
x <- 1:3
typeof(x)
typeof(as.character(x))
```

```{r}
c(1, "Hello")
c(1, "Hello")
c(1.2, 3L)
c(2L, "two")
```

##Special Values
```{r}
pi/0
0/0
1/0 - 1/0
1/0 + 1/0
```

```{r}
#NA: Not available, NaN: Not a number, Inf: Positive infinity, -Inf: Negative infinity
x <- c(1,2,3,4,NA)
mean(x)
mean(x, na.ra = TRUE)
summary(x)
```

```{r}
#R uses NA to represent missing values in its data structures.
typeof(NA)
```
```{r}
# TRUE or NA
TRUE | NA
# FALSE or NA
FALSE | NA
TRUE | TRUE  # if NA was TRUE
TRUE | FALSE # if NA was FALSE
FALSE | TRUE  # if NA was TRUE
FALSE | FALSE # if NA was FALSE
```

