---
title: A02
author: R package build
date: '2022-03-25'
slug: a02
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
## ✓ tibble  3.1.6     ✓ dplyr   1.0.8
## ✓ tidyr   1.2.0     ✓ stringr 1.4.0
## ✓ readr   2.1.2     ✓ forcats 0.5.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(boot)
library(patchwork)
df &lt;- read.csv(file = &#39;https://raw.githubusercontent.com/ellaprotz/webstie_ella/master/Professor_Proposes_Data_Final.csv&#39;)</code></pre>
<pre class="r"><code>summary(df)</code></pre>
<pre><code>##      Carat           Colour            Clarity              Cut           
##  Min.   :0.0900   Length:440         Length:440         Length:440        
##  1st Qu.:0.3000   Class :character   Class :character   Class :character  
##  Median :0.8100   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :0.6693                                                           
##  3rd Qu.:1.0100                                                           
##  Max.   :1.5800                                                           
##  Certification         Polish            Symmetry             Price     
##  Length:440         Length:440         Length:440         Min.   : 160  
##  Class :character   Class :character   Class :character   1st Qu.: 520  
##  Mode  :character   Mode  :character   Mode  :character   Median :2169  
##                                                           Mean   :1717  
##                                                           3rd Qu.:3012  
##                                                           Max.   :3145  
##    Wholesaler   
##  Min.   :1.000  
##  1st Qu.:2.000  
##  Median :2.000  
##  Mean   :2.318  
##  3rd Qu.:3.000  
##  Max.   :3.000</code></pre>
<div id="frequiencies-of-each-variable" class="section level2">
<h2>Frequiencies of each variable</h2>
<pre class="r"><code>df %&gt;% count(Cut)</code></pre>
<pre><code>##   Cut   n
## 1   F  59
## 2   G  49
## 3   I  86
## 4   V  97
## 5   X 149</code></pre>
<pre class="r"><code>cut &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Cut, fill = Cut)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Clarity)</code></pre>
<pre><code>##   Clarity   n
## 1      I1  82
## 2      I2  28
## 3     SI1 116
## 4     SI2 110
## 5     SI3  26
## 6     VS1  30
## 7     VS2  41
## 8    VVS1   2
## 9    VVS2   5</code></pre>
<pre class="r"><code>clarity &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Clarity, fill = Clarity)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Certification)</code></pre>
<pre><code>##   Certification   n
## 1           AGS  12
## 2           DOW   1
## 3           EGL 119
## 4           GIA 265
## 5           IGI  43</code></pre>
<pre class="r"><code>certification &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Certification, fill = Certification)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Polish)</code></pre>
<pre><code>##   Polish   n
## 1      F   5
## 2      G 165
## 3      I   5
## 4      v   1
## 5      V 203
## 6      X  61</code></pre>
<pre class="r"><code>polish &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Polish, fill = Polish)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Symmetry)</code></pre>
<pre><code>##   Symmetry   n
## 1        F  21
## 2        G 157
## 3        I   5
## 4        V 206
## 5        X  51</code></pre>
<pre class="r"><code>symmetry &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Symmetry, fill = Symmetry)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )
cut + clarity + certification + polish + symmetry</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="comparison-of-variables-with-price-boxplots" class="section level2">
<h2>Comparison of Variables with Price, Boxplots</h2>
<pre class="r"><code>carat &lt;- ggplot(data = df, 
       mapping = aes(x = Carat, y = Price,
                     colour = Wholesaler)) +
  geom_point() 
color &lt;- ggplot (df, aes(x = Colour, y = Price)) +
  geom_boxplot()
cut &lt;- ggplot (df, aes(x = Cut, y = Price)) +
  geom_boxplot()
clarity &lt;- ggplot (df, aes(x = Clarity, y = Price)) +
  geom_boxplot()
certification &lt;- ggplot (df, aes(x = Certification, y = Price)) +
  geom_boxplot()
polish &lt;- ggplot (df, aes(x = Polish, y = Price)) +
  geom_boxplot()
symmetry &lt;- ggplot (df, aes(x = Symmetry, y = Price)) +
  geom_boxplot()
 carat + cut + color + clarity + certification + polish + symmetry </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-1.png" width="672" />
### Bases on the graphs, it shows that the Carat and color has the most impact on price. As Carat increases, the price increases. It also shows that for colors J, K, L all have a higher price, which falls within the Faint yellow and light yellow. D has the highest price which is completely colorless and G which is Near colorless also has very high price. By looking at the chart, and those two factors, the diamond will come out to be around $2500, by just looking. The other boxplots have variation in them, showing that there isn’t much correlation between them and price. For example, despite the polish going from Fair to Excelet, the price does not increase as the Polish quality increases, so therefor it shows that that variable does not have much impact on the price. On average, based on all of the factors that go into pricing, we can estimate the price will fall under $3000, so it is under the Professors price.</p>
</div>
<div id="effect-of-variables-on-the-carat" class="section level2">
<h2>Effect of Variables on the Carat</h2>
<pre class="r"><code>cut &lt;- ggplot (df, aes(x = Cut, y = Carat)) +
  geom_boxplot()
color &lt;- ggplot (df, aes(x = Colour, y = Carat)) +
  geom_boxplot()
clarity &lt;- ggplot (df, aes(x = Clarity, y = Carat)) +
  geom_boxplot()
certification &lt;- ggplot (df, aes(x = Certification, y = Carat)) +
  geom_boxplot()
polish &lt;- ggplot (df, aes(x = Polish, y = Carat)) +
  geom_boxplot()
symmetry &lt;- ggplot (df, aes(x = Symmetry, y = Carat)) +
  geom_boxplot()
cut +  color + clarity + certification + polish + symmetry </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-5-1.png" width="672" />
### Basesd on the graphs, it shows that there are no variables that impact the Carat of the diamond, which is the main impact on price.</p>
</div>
<div id="linear-regression-model" class="section level2">
<h2>Linear Regression Model</h2>
<pre class="r"><code>model &lt;- lm(Price~Carat, data = df)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Price ~ Carat, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1705.8  -165.9  -111.9   135.2   994.7 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -200.48      43.11   -4.65  4.4e-06 ***
## Carat        2864.73      56.04   51.12  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 446 on 438 degrees of freedom
## Multiple R-squared:  0.8564, Adjusted R-squared:  0.8561 
## F-statistic:  2613 on 1 and 438 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="therefore-the-equation-of-price-based-on-just-carats-is-y--200.48-2864.73x.-the-r-squared-value-is-.8564-indicating-it-is-a-pretty-decent-model-of-fit-for-linear-regression.-it-is-not-the-strongest-but-it-is-still-pretty-good." class="section level2">
<h2>Therefore the equation of Price based on just Carats is y = -200.48 + 2864.73x. The R-squared value is .8564, indicating it is a pretty decent model of fit for Linear Regression. It is not the strongest, but it is still pretty good.</h2>
<pre class="r"><code>plot(model)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-2.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-3.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-4.png" width="672" /></p>
</div>
<div id="regression-model-for-all-variables" class="section level2">
<h2>Regression model for all variables</h2>
<pre class="r"><code>model &lt;- lm(Price~Carat + Colour + Clarity + Polish + Symmetry + Certification, data = df)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Price ~ Carat + Colour + Clarity + Polish + Symmetry + 
##     Certification, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -770.27  -79.65  -23.07   96.03  720.13 
## 
## Coefficients: (1 not defined because of singularities)
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      -1419.0008   145.7010  -9.739  &lt; 2e-16 ***
## Carat             4203.8547    51.3735  81.829  &lt; 2e-16 ***
## ColourE           -176.9469    53.3184  -3.319 0.000985 ***
## ColourF           -297.1051    53.4217  -5.562 4.83e-08 ***
## ColourG           -296.9269    54.3670  -5.462 8.20e-08 ***
## ColourH           -432.4950    53.0893  -8.147 4.57e-15 ***
## ColourI           -498.2592    53.1198  -9.380  &lt; 2e-16 ***
## ColourJ           -639.0323    54.6541 -11.692  &lt; 2e-16 ***
## ColourK           -985.8307    60.7977 -16.215  &lt; 2e-16 ***
## ColourL          -1172.9779    76.2019 -15.393  &lt; 2e-16 ***
## ClarityI2         -781.6719    50.6492 -15.433  &lt; 2e-16 ***
## ClaritySI1         871.7790    42.3892  20.566  &lt; 2e-16 ***
## ClaritySI2         743.0806    34.9045  21.289  &lt; 2e-16 ***
## ClaritySI3         396.4986    48.9463   8.101 6.33e-15 ***
## ClarityVS1        1040.0817    58.4944  17.781  &lt; 2e-16 ***
## ClarityVS2         927.4092    52.9021  17.531  &lt; 2e-16 ***
## ClarityVVS1       1351.7533   154.7225   8.737  &lt; 2e-16 ***
## ClarityVVS2        902.2643   100.7400   8.956  &lt; 2e-16 ***
## PolishG            219.6188   106.5724   2.061 0.039957 *  
## PolishI            528.8674   151.9493   3.481 0.000554 ***
## Polishv            203.4980   229.1785   0.888 0.375091    
## PolishV            239.0426   110.3181   2.167 0.030822 *  
## PolishX            250.5717   113.5260   2.207 0.027855 *  
## SymmetryG          132.3797    55.6611   2.378 0.017849 *  
## SymmetryI                NA         NA      NA       NA    
## SymmetryV          153.6717    58.6488   2.620 0.009114 ** 
## SymmetryX          156.7214    65.5892   2.389 0.017325 *  
## CertificationDOW  -515.9997   223.3059  -2.311 0.021343 *  
## CertificationEGL  -429.9571    81.4648  -5.278 2.12e-07 ***
## CertificationGIA   -65.3215    80.2159  -0.814 0.415933    
## CertificationIGI     0.5171    93.9241   0.006 0.995610    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 197.7 on 410 degrees of freedom
## Multiple R-squared:  0.9736, Adjusted R-squared:  0.9717 
## F-statistic: 521.4 on 29 and 410 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="the-equation-for-price-based-on-carat-and-all-the-factors-is-y--1419.008-4203.8547x.-the-r-squared-value-is-.9736-indicating-this-linear-model-is-a-very-good-fit." class="section level2">
<h2>The equation for Price based on Carat and all the factors is y = -1419.008 + 4203.8547x. The R-Squared value is .9736, indicating this linear model is a very good fit.</h2>
<pre class="r"><code>plot(model)</code></pre>
<pre><code>## Warning: not plotting observations with leverage one:
##   55</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-1.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-2.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-3.png" width="672" /></p>
<pre><code>## Warning in sqrt(crit * p * (1 - hh)/hh): NaNs produced</code></pre>
<pre><code>## Warning in sqrt(crit * p * (1 - hh)/hh): NaNs produced</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-4.png" width="672" /></p>
</div>
<div id="bootstrap-validation" class="section level2">
<h2>Bootstrap Validation</h2>
<pre class="r"><code>set.seed(1)
head(df)</code></pre>
<pre><code>##   Carat Colour Clarity Cut Certification Polish Symmetry Price Wholesaler
## 1  0.92      I     SI2   G           AGS      V        V  3000          1
## 2  0.92      I     SI2   V           AGS      G        G  3000          1
## 3  0.82      F     SI2   I           GIA      X        X  3004          1
## 4  0.81      G     SI1   I           GIA      X        V  3004          1
## 5  0.90      J     VS2   V           GIA      V        V  3006          1
## 6  0.87      F     SI2   I           AGS      G        V  3007          1</code></pre>
<pre class="r"><code>dim(df)</code></pre>
<pre><code>## [1] 440   9</code></pre>
<pre class="r"><code>train &lt;- sample(440, 220)
head(train)</code></pre>
<pre><code>## [1] 324 167 129 418 299 270</code></pre>
<pre class="r"><code>boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Carat, data = df, subset = index)))
}</code></pre>
<pre class="r"><code>boot.fn(Auto, 1:440)</code></pre>
<pre><code>## (Intercept)       Carat 
##   -200.4836   2864.7325</code></pre>
<pre class="r"><code>set.seed(1)
boot.fn(df, sample(440, 440, replace = T))</code></pre>
<pre><code>## (Intercept)       Carat 
##   -234.7978   2914.3759</code></pre>
<pre class="r"><code>boot(df, boot.fn, 100)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = df, statistic = boot.fn, R = 100)
## 
## 
## Bootstrap Statistics :
##      original     bias    std. error
## t1* -200.4836  0.7538073    22.43823
## t2* 2864.7325 -1.8791241    52.11863</code></pre>
<pre class="r"><code>boot.out &lt;- boot(df, boot.fn, 100)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre class="r"><code>boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Carat, data = df, subset = index)))
}
boot.fn(df, 1:440)</code></pre>
<pre><code>## (Intercept)       Carat 
##   -200.4836   2864.7325</code></pre>
<pre class="r"><code>boot(df, boot.fn, 1000)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = df, statistic = boot.fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##      original     bias    std. error
## t1* -200.4836  0.9722933    24.78080
## t2* 2864.7325 -2.4179982    55.60644</code></pre>
<pre class="r"><code>boot.out &lt;- boot(df, boot.fn, 1000)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
<div id="the-final-price-we-can-predict-the-diamond-to-be-based-on-will-be" class="section level2">
<h2>The final price we can predict the diamond to be based on will be:</h2>
<ol style="list-style-type: decimal">
<li>Equation 1: $2,377.78</li>
<li>Equation 2: $2,364.46</li>
</ol>
<p>Based on the two numbers, it will fall under the Professors budget and that the factors like color, clarity, cut etc do not have much impact on the pricing of the diamond.</p>
</div>
