---
title: A02 Revised
author: R package build
date: '2022-03-30'
slug: a02-revised
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
## ✓ tibble  3.1.6     ✓ dplyr   1.0.8
## ✓ tidyr   1.2.0     ✓ stringr 1.4.0
## ✓ readr   2.1.2     ✓ forcats 0.5.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(boot)
library(patchwork)
df &lt;- read.csv(file = &#39;https://raw.githubusercontent.com/ellaprotz/webstie_ella/master/Professor_Proposes_Data_Final.csv&#39;)</code></pre>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<pre class="r"><code>df %&gt;% count(Colour)</code></pre>
<pre><code>##   Colour  n
## 1      D 20
## 2      E 54
## 3      F 58
## 4      G 43
## 5      H 71
## 6      I 79
## 7      J 72
## 8      K 31
## 9      L 12</code></pre>
<pre class="r"><code>color &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Colour, fill = Cut)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Cut)</code></pre>
<pre><code>##   Cut   n
## 1   F  59
## 2   G  49
## 3   I  86
## 4   V  97
## 5   X 149</code></pre>
<pre class="r"><code>cut &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Cut, fill = Cut)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Clarity)</code></pre>
<pre><code>##   Clarity   n
## 1      I1  82
## 2      I2  28
## 3     SI1 116
## 4     SI2 110
## 5     SI3  26
## 6     VS1  30
## 7     VS2  41
## 8    VVS1   2
## 9    VVS2   5</code></pre>
<pre class="r"><code>clarity &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Clarity, fill = Clarity)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Certification)</code></pre>
<pre><code>##   Certification   n
## 1           AGS  12
## 2           DOW   1
## 3           EGL 119
## 4           GIA 265
## 5           IGI  43</code></pre>
<pre class="r"><code>certification &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Certification, fill = Certification)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Polish)</code></pre>
<pre><code>##   Polish   n
## 1      F   5
## 2      G 165
## 3      I   5
## 4      v   1
## 5      V 203
## 6      X  61</code></pre>
<pre class="r"><code>polish &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Polish, fill = Polish)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )

df %&gt;% count(Symmetry)</code></pre>
<pre><code>##   Symmetry   n
## 1        F  21
## 2        G 157
## 3        I   5
## 4        V 206
## 5        X  51</code></pre>
<pre class="r"><code>symmetry &lt;- df %&gt;%
  ggplot() +
  geom_bar(aes(Symmetry, fill = Symmetry)) +
  theme(
    axis.title.x = element_blank(),
    legend.position = &quot;none&quot;
  )
color + cut + clarity + certification + polish + symmetry</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>carat &lt;- ggplot(data = df, 
       mapping = aes(x = Carat, y = Price,
                     colour = Wholesaler)) +
  geom_point()
color &lt;- ggplot (df, aes(x = Colour, y = Price)) +
  geom_boxplot()
cut &lt;- ggplot (df, aes(x = Cut, y = Price)) +
  geom_boxplot()
clarity &lt;- ggplot (df, aes(x = Clarity, y = Price)) +
  geom_boxplot()
certification &lt;- ggplot (df, aes(x = Certification, y = Price)) +
  geom_boxplot()
polish &lt;- ggplot (df, aes(x = Polish, y = Price)) +
  geom_boxplot()
symmetry &lt;- ggplot (df, aes(x = Symmetry, y = Price)) +
  geom_boxplot()
 carat + cut + color + clarity + certification + polish + symmetry </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-1.png" width="672" />
### Bases on the graphs, it shows that the Carat and color has the most impact on price. As Carat increases, the price increases. It also shows that for colors J, K, L all have a higher price, which falls within the Faint yellow and light yellow. D has the highest price which is completely colorless and G which is Near colorless also has very high price. By looking at the chart, and those two factors, the diamond will come out to be around $2500, by just looking. The other boxplots have variation in them, showing that there isn’t much correlation between them and price. For example, despite the polish going from Fair to Excelet, the price does not increase as the Polish quality increases, so therefor it shows that that variable does not have much impact on the price. On average, based on all of the factors that go into pricing, we can estimate the price will fall under $3000, so it is under the Professors price.</p>
</div>
<div id="also-based-on-the-point-graph-there-is-a-clump-of-carats-from-just-wholesaler-3-that-causes-a-skew-in-our-a-data-so-we-can-disregard-that-any-data-from-wholesaler-3." class="section level2">
<h2>Also based on the point graph, there is a clump of carats from just wholesaler 3 that causes a skew in our a data, so we can disregard that any data from wholesaler 3.</h2>
</div>
<div id="new-data-frame" class="section level1">
<h1>New data frame</h1>
<pre class="r"><code>df1 &lt;- df %&gt;%
  filter(Wholesaler!=3)</code></pre>
</div>
<div id="manipulating" class="section level1">
<h1>Manipulating</h1>
<pre class="r"><code>sapply(df1, function (x) length(unique(x)))</code></pre>
<pre><code>##         Carat        Colour       Clarity           Cut Certification 
##            40             9             7             5             4 
##        Polish      Symmetry         Price    Wholesaler 
##             6             5           172             2</code></pre>
<pre class="r"><code>df1$Colour &lt;- as.factor(df1$Colour)
df1$Clarity &lt;- as.factor(df1$Clarity)
df1$Cut &lt;- as.factor(df1$Cut)
df1$Certification &lt;- as.factor(df1$Certification)
df1$Polish &lt;- as.factor(df1$Polish)
df1$Symmetry &lt;- as.factor(df1$Symmetry)
str(df1)</code></pre>
<pre><code>## &#39;data.frame&#39;:    240 obs. of  9 variables:
##  $ Carat        : num  0.92 0.92 0.82 0.81 0.9 0.87 0.8 0.84 0.8 0.8 ...
##  $ Colour       : Factor w/ 9 levels &quot;D&quot;,&quot;E&quot;,&quot;F&quot;,&quot;G&quot;,..: 6 6 3 4 7 3 1 3 1 1 ...
##  $ Clarity      : Factor w/ 7 levels &quot;I1&quot;,&quot;I2&quot;,&quot;SI1&quot;,..: 4 4 4 3 7 4 4 3 4 4 ...
##  $ Cut          : Factor w/ 5 levels &quot;F&quot;,&quot;G&quot;,&quot;I&quot;,&quot;V&quot;,..: 2 4 3 3 4 3 3 2 4 4 ...
##  $ Certification: Factor w/ 4 levels &quot;AGS&quot;,&quot;DOW&quot;,&quot;EGL&quot;,..: 1 1 4 4 4 1 4 4 4 4 ...
##  $ Polish       : Factor w/ 6 levels &quot;F&quot;,&quot;G&quot;,&quot;I&quot;,&quot;v&quot;,..: 5 2 6 6 5 2 5 5 5 5 ...
##  $ Symmetry     : Factor w/ 5 levels &quot;F&quot;,&quot;G&quot;,&quot;I&quot;,&quot;V&quot;,..: 4 2 5 4 4 4 4 4 4 5 ...
##  $ Price        : int  3000 3000 3004 3004 3006 3007 3008 3010 3012 3012 ...
##  $ Wholesaler   : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<pre class="r"><code>model &lt;- lm(Price~., data =df1)
model</code></pre>
<pre><code>## 
## Call:
## lm(formula = Price ~ ., data = df1)
## 
## Coefficients:
##      (Intercept)             Carat           ColourE           ColourF  
##           394.78           2104.61           -125.91           -314.20  
##          ColourG           ColourH           ColourI           ColourJ  
##          -248.19           -327.37           -390.34           -533.50  
##          ColourK           ColourL         ClarityI2        ClaritySI1  
##          -808.12           -979.94           -595.53            781.68  
##       ClaritySI2        ClaritySI3        ClarityVS1        ClarityVS2  
##           646.89            331.39            897.19            870.70  
##             CutG              CutI              CutV              CutX  
##            18.69             90.75             73.79             98.99  
## CertificationDOW  CertificationEGL  CertificationGIA           PolishG  
##          -349.42           -359.92            -29.26             72.21  
##          PolishI           Polishv           PolishV           PolishX  
##           172.81            187.85            101.41            104.37  
##        SymmetryG         SymmetryI         SymmetryV         SymmetryX  
##           124.36                NA            122.24             93.53  
##       Wholesaler  
##           176.44</code></pre>
<pre class="r"><code>summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Price ~ ., data = df1)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -436.5 -108.4    0.0  108.5  572.2 
## 
## Coefficients: (1 not defined because of singularities)
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        394.78     233.06   1.694   0.0918 .  
## Carat             2104.61     186.12  11.308  &lt; 2e-16 ***
## ColourE           -125.91      61.10  -2.061   0.0406 *  
## ColourF           -314.20      64.88  -4.843 2.49e-06 ***
## ColourG           -248.19      61.81  -4.015 8.30e-05 ***
## ColourH           -327.37      62.46  -5.241 3.90e-07 ***
## ColourI           -390.34      62.32  -6.264 2.12e-09 ***
## ColourJ           -533.50      64.24  -8.304 1.28e-14 ***
## ColourK           -808.12      70.28 -11.498  &lt; 2e-16 ***
## ColourL           -979.94      80.97 -12.103  &lt; 2e-16 ***
## ClarityI2         -595.53      51.72 -11.514  &lt; 2e-16 ***
## ClaritySI1         781.68      60.57  12.906  &lt; 2e-16 ***
## ClaritySI2         646.89      44.81  14.437  &lt; 2e-16 ***
## ClaritySI3         331.39      48.51   6.832 9.08e-11 ***
## ClarityVS1         897.19      94.16   9.529  &lt; 2e-16 ***
## ClarityVS2         870.70      91.21   9.546  &lt; 2e-16 ***
## CutG                18.69      44.29   0.422   0.6735    
## CutI                90.75      48.99   1.852   0.0654 .  
## CutV                73.79      58.52   1.261   0.2088    
## CutX                98.99      38.72   2.557   0.0113 *  
## CertificationDOW  -349.42     213.25  -1.639   0.1028    
## CertificationEGL  -359.92      89.92  -4.002 8.72e-05 ***
## CertificationGIA   -29.26      79.70  -0.367   0.7139    
## PolishG             72.21     101.78   0.709   0.4788    
## PolishI            172.81     160.80   1.075   0.2838    
## Polishv            187.85     221.48   0.848   0.3973    
## PolishV            101.41     108.45   0.935   0.3509    
## PolishX            104.37     118.42   0.881   0.3792    
## SymmetryG          124.36      55.45   2.243   0.0260 *  
## SymmetryI              NA         NA      NA       NA    
## SymmetryV          122.24      61.57   1.985   0.0484 *  
## SymmetryX           93.53      78.56   1.190   0.2352    
## Wholesaler         176.44      72.25   2.442   0.0154 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 184.8 on 208 degrees of freedom
## Multiple R-squared:  0.7798, Adjusted R-squared:  0.747 
## F-statistic: 23.76 on 31 and 208 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="the-regression-model-that-i-used-was-predicting-price-on-all-of-the-different-variables.-using-this-chart-we-can-go-through-and-pick-out-the-characteristics-the-professor-wants-for-his-ring.-the-data-is-as-follows-394.78-intercept-2104.61-per-carat--533.50-for-color-j-646.89-for-clarity-s12-73.79-for-cut-v--29.26-for-certification-gia-72.21-for-polish-g-and-122.24-for-symmetry-v.-we-can-now-add-up-each-value-to-get-the-total-predicted-price-for-the-diamond-ring." class="section level2">
<h2>The regression model that I used was predicting price on all of the different variables. Using this chart, we can go through and pick out the characteristics the professor wants for his ring. The data is as follows: 394.78 intercept, 2104.61 per carat, -533.50 for color J, 646.89 for Clarity S12, 73.79 for cut V, -29.26 for certification GIA, 72.21 for Polish G, and 122.24 for Symmetry V. We can now add up each value to get the total predicted price for the diamond ring.</h2>
<pre class="r"><code>plot(model)</code></pre>
<pre><code>## Warning: not plotting observations with leverage one:
##   55, 68</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-1.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-2.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-3.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-4.png" width="672" /></p>
<pre class="r"><code>anova(model, test=&quot;Chisq&quot;)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Price
##                Df   Sum Sq Mean Sq  F value    Pr(&gt;F)    
## Carat           1  3456697 3456697 101.2258 &lt; 2.2e-16 ***
## Colour          8  1885061  235633   6.9003 4.772e-08 ***
## Clarity         6 15503423 2583904  75.6670 &lt; 2.2e-16 ***
## Cut             4  1445160  361290  10.5800 8.020e-08 ***
## Certification   3  2320149  773383  22.6477 9.948e-13 ***
## Polish          5   197540   39508   1.1570   0.33165    
## Symmetry        3   142990   47663   1.3958   0.24514    
## Wholesaler      1   203683  203683   5.9647   0.01543 *  
## Residuals     208  7102861   34148                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="adding-all-of-the-factors-together-there-is-a-grand-total-of-2641.30-for-the-diamond-the-professor-wants-to-buy." class="section level2">
<h2>Adding all of the factors together, there is a grand total of $2641.30 for the diamond the professor wants to buy.</h2>
</div>
<div id="bootstrap-validation" class="section level2">
<h2>Bootstrap Validation</h2>
<pre class="r"><code>set.seed(1)
head(df1)</code></pre>
<pre><code>##   Carat Colour Clarity Cut Certification Polish Symmetry Price Wholesaler
## 1  0.92      I     SI2   G           AGS      V        V  3000          1
## 2  0.92      I     SI2   V           AGS      G        G  3000          1
## 3  0.82      F     SI2   I           GIA      X        X  3004          1
## 4  0.81      G     SI1   I           GIA      X        V  3004          1
## 5  0.90      J     VS2   V           GIA      V        V  3006          1
## 6  0.87      F     SI2   I           AGS      G        V  3007          1</code></pre>
<pre class="r"><code>dim(df1)</code></pre>
<pre><code>## [1] 240   9</code></pre>
<pre class="r"><code>train &lt;- sample(240, 120)
head(train)</code></pre>
<pre><code>## [1]  68 167 129 162 215  43</code></pre>
</div>
<div id="boostrap-for-carat-and-price" class="section level2">
<h2>Boostrap for Carat and Price</h2>
<pre class="r"><code>boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Carat, data = df1, subset = index)))
}
boot.fn(Auto, 1:240)</code></pre>
<pre><code>## (Intercept)       Carat 
##   3740.9843   -980.6041</code></pre>
<pre class="r"><code>set.seed(1)
boot.fn(df1, sample(240, 240, replace = T))</code></pre>
<pre><code>## (Intercept)       Carat 
##    3751.822   -1002.177</code></pre>
<pre class="r"><code>boot(df1, boot.fn, 100)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = df1, statistic = boot.fn, R = 100)
## 
## 
## Bootstrap Statistics :
##      original    bias    std. error
## t1* 3740.9843  15.99046    174.6983
## t2* -980.6041 -15.51681    182.1766</code></pre>
<pre class="r"><code>boot.out &lt;- boot(df1, boot.fn, 100)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Carat, data = df1, subset = index)))
}
boot.fn(df1, 1:220)</code></pre>
<pre><code>## (Intercept)       Carat 
##    3802.918   -1046.850</code></pre>
<pre class="r"><code>boot(df1, boot.fn, 1000)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = df1, statistic = boot.fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##      original    bias    std. error
## t1* 3740.9843  11.59247    160.6828
## t2* -980.6041 -13.56441    168.0413</code></pre>
<pre class="r"><code>boot.out &lt;- boot(df1, boot.fn, 1000)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
</div>
<div id="bootstrap-for-colour-and-price" class="section level2">
<h2>Bootstrap for Colour and Price</h2>
<pre class="r"><code>boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Colour, data = df1, subset = index)))
}
boot.fn(Auto, 1:240)</code></pre>
<pre><code>## (Intercept)     ColourE     ColourF     ColourG     ColourH     ColourI 
##   2952.9333   -124.5487   -239.6833   -140.4817   -198.1402   -174.8778 
##     ColourJ     ColourK     ColourL 
##   -146.3583   -322.3407   -584.4333</code></pre>
<pre class="r"><code>set.seed(1)
boot.fn(df1, sample(240, 240, replace = T))</code></pre>
<pre><code>## (Intercept)     ColourE     ColourF     ColourG     ColourH     ColourI 
##  2874.60000    28.06667  -139.93333  -181.63226   -61.56970  -102.28182 
##     ColourJ     ColourK     ColourL 
##  -103.92432  -180.10000  -559.60000</code></pre>
<pre class="r"><code>boot(df1, boot.fn, 100)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = df1, statistic = boot.fn, R = 100)
## 
## 
## Bootstrap Statistics :
##      original     bias    std. error
## t1* 2952.9333  4.5395183    46.22484
## t2* -124.5487 -4.7996703    78.94899
## t3* -239.6833 -2.9046662    93.73425
## t4* -140.4817 -4.9221111    81.07984
## t5* -198.1402 -8.9113252    84.70541
## t6* -174.8778 -2.6936958    68.54678
## t7* -146.3583  0.8396408    73.29905
## t8* -322.3407  4.9404381    79.80381
## t9* -584.4333 -8.5983083   115.24889</code></pre>
<pre class="r"><code>boot.out &lt;- boot(df1, boot.fn, 100)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Colour, data = df1, subset = index)))
}
boot.fn(df1, 1:220)</code></pre>
<pre><code>## (Intercept)     ColourE     ColourF     ColourG     ColourH     ColourI 
##   3038.5455   -203.0871   -329.5455   -223.5455   -283.7524   -260.4899 
##     ColourJ     ColourK     ColourL 
##   -224.4597   -419.3371   -749.8455</code></pre>
<pre class="r"><code>boot(df1, boot.fn, 1000)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = df1, statistic = boot.fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##      original       bias    std. error
## t1* 2952.9333  0.008243498    49.71093
## t2* -124.5487  2.096002715    79.74241
## t3* -239.6833 -1.731007443    86.66330
## t4* -140.4817 -0.368393795    80.45138
## t5* -198.1402 -5.638687079    89.14197
## t6* -174.8778 -0.086400358    83.38398
## t7* -146.3583 -2.151230868    77.91441
## t8* -322.3407 -1.222242952    77.48475
## t9* -584.4333  2.555840987    98.63602</code></pre>
<pre class="r"><code>boot.out &lt;- boot(df1, boot.fn, 1000)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
</div>
<div id="boostrap-for-clarity-and-price" class="section level2">
<h2>Boostrap for Clarity and Price</h2>
<pre class="r"><code>boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Clarity, data = df1, subset = index)))
}
boot.fn(Auto, 1:240)</code></pre>
<pre><code>## (Intercept)   ClarityI2  ClaritySI1  ClaritySI2  ClaritySI3  ClarityVS1 
## 2622.911392 -280.982821  376.607126  368.011685   -3.526777  431.713608 
##  ClarityVS2 
##  380.517179</code></pre>
<pre class="r"><code>set.seed(1)
boot.fn(df1, sample(240, 240, replace = T))</code></pre>
<pre><code>## (Intercept)   ClarityI2  ClaritySI1  ClaritySI2  ClaritySI3  ClarityVS1 
##  2627.88312  -311.94562   372.75325   333.90793    30.46982   419.51688 
##  ClarityVS2 
##   328.11688</code></pre>
<pre class="r"><code>boot(df1, boot.fn, 100)</code></pre>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = df1, statistic = boot.fn, R = 100)
## 
## 
## Bootstrap Statistics :
##        original      bias    std. error
## t1* 2622.911392  4.20510695    39.02084
## t2* -280.982821 -9.09621901    60.46483
## t3*  376.607126 -1.42275166    47.84533
## t4*  368.011685  0.09486799    46.83047
## t5*   -3.526777  1.72671938   100.75521
## t6*  431.713608 -7.14706010    40.29867
## t7*  380.517179 -5.03786566    82.30947</code></pre>
<pre class="r"><code>boot.out &lt;- boot(df1, boot.fn, 100)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="i-did-a-boostrap-model-for-clarity-colour-and-carat-becuase-those-are-the-three-most-important-factors-of-the-pricing." class="section level2">
<h2>I did a boostrap model for Clarity, Colour and Carat becuase those are the three most important factors of the pricing.</h2>
</div>
</div>
